# Data Types and Structures Questions

1. What are data structures, and why are they important?
  - Data structures ar way to orgnize and store data in a computer so that it can be accessed and used efficiently. They define how data is arranged, related, and accessed. They are containers that hold and manage our data.
  - Importance: efficient data orgnation, optimized operations, data integrity and code readability and maintainability.

2. Explain the difference between mutable and immutable data types with examples.
  - Mutable Data Types: These can be changed after they're created. We can modify, add, or remove elements in-place.
  Example:  List, Dictionary, Set
  - These cannot be changed after creation. Any operation that modifies them will create a new object.
  Example: String, Tuple, Integer, Float, Boolean.

3. What are the main differences between lists and tuples in Python?
  - The main difference between Lists and Tuples. Tuples are mutable their elements can be added, removed, or modified after creation. But Tuples are immutable, meaning their elements cannot be changed once the tuple is created.

4. Describe how dictionaries store data.
  - Dictionaries are unordered collections of data and are represented with curly brackets { } . Dictionaries are mutable and indexed. Dictionaries store data in  key:value format.

5. Why might you use a set instead of a list in Python?
  - Sets store only unique elements. If I need a collection where duplicate values are not allowed, a set automatically handles this. Lists allows duplicates.

6. What is a string in Python, and how is it different from a list?
  - Strings in Python are sequences of characters enclosed in quotes ('' or “”). Lists are ordered collections of items enclosed in square brackets []. Strings are immutable,  they cannot be changed once created, while lists are mutable and can be modified as needed.

7. How do tuples ensure data integrity in Python?
  - Once a tuple is created, its elements cannot be changed, added, or removed. Any attempt to modify a tuple after its creation will result in a TypeError. This fundamental characteristic directly contributes to data integrity.

8. What is a hash table, and how does it relate to dictionaries in Python?
  - A hash table is a data structure that implements an associative array, also known as a dictionary or map. It stores key-value pairs by using a hash function to compute an index into an array of buckets or slots, from which the desired value can be retrieved. This allows for efficient insertion, deletion, and lookup operations.

9. Can lists contain different data types in Python?
  - Yes, lists in Python can contain elements of different data types. This is a key feature of Python lists, making them highly versatile.

10. Explain why strings are immutable in Python.
  - Strings are immutable in Python, meaning their content cannot be changed after they are created.

11. What advantages do dictionaries offer over lists for certain tasks?
  - Dictionaries are fast lookups, key-value associations, and complex data mappings, while lists are ideal for ordered collections, sequential processing, and simple data storage.

12. Describe a scenario where using a tuple would be preferable over a list.
  - I use a list for mutable collection of items where I need to add, remove, or change elements. Lists are more flexible and have more built-in methods, making them ideal for dynamic collections. I use a tuple if I need an immutable collection where the elements won't change after creation.

13. How do sets handle duplicate values in Python?
  - When an attempt is made to add an element that already exists within a set, the set simply ignores the addition and remains unchanged.

14. How does the “in” keyword work differently for lists and dictionaries?
  - In list "in" checks for element(value) and In dictionaries "in" checks for key.

15. Can you modify the elements of a tuple? Explain why or why not?
  - We cannot directly modify the elements of a tuple in Python. Tuples are immutable, meaning their contents cannot be changed after creation. If we attempt to modify a tuple, we will get a TypeError.

16. What is a nested dictionary, and give an example of its use case.
  - A nested dictionary in Python is a dictionary that contains other dictionaries as its values.
  - EX. employees = {
    "emp1": {
        "name": "Alice",
        "age": 30,
        "address": {
            "city": "New York",
            "zipcode": "10001"
        }
    },
    "emp2": {
        "name": "Bob",
        "age": 25,
        "address": {
            "city": "Los Angeles",
            "zipcode": "90001"
        }
    }
}

17. Describe the time complexity of accessing elements in a dictionary.
  - Accessing elements in a dictionary typically has a time complexity of O(1) on average. This means that the time it takes to retrieve a value by its key is, on average, constant and doesn't depend on the size of the dictionary. However, in the worst-case scenario, the time complexity can be O(n), where n is the number of elements in the dictionary, due to hash collisions.

18. In what situations are lists preferred over dictionaries?
  - if I need an ordered collection, like a sequence of user actions. On the other hand, when we need quick look-ups, like mapping usernames to user data, dictionaries are preferred.

19. Why are dictionaries considered unordered, and how does that affect data retrieval?
  - A dictionary is considered an unordered collection because it doesn't store items in a specific sequence that corresponds to insertion order. Unlike lists or tuples, we can't rely on the order in which we added elements to a dictionary when retrieving them. Dictionaries are optimized for key-based lookups, not for maintaining order.

20. Explain the difference between a list and a dictionary in terms of data retrieval.
  - A list is an ordered collection of items, whereas a dictionary is an unordered data collection in a key: value pair. Elements from the list can be accessed using the index, while the elements of the dictionary can be accessed using keys.

# Practical Questions

In [1]:
# 1. Write a code to create a string with your name and print it.
name = "Ram"
print(name)

Ram

In [2]:
# 2. Write a code to find the length of the string "Hello World".
strng = "Hello World"
length = len(strng)
print("Length of the string:", length)

Length of the string: 11

In [3]:
# 3. Write a code to slice the first 3 characters from the string "Python Programming".
text = "Python Programming"
sliced = text[:3]
print(sliced)

Pyt

In [7]:
# 4. Write a code to convert the string "hello" to uppercase.
strng = "hello"
upper_case = strng.upper()
print(upper_case)

HELLO

In [8]:
# 5. Write a code to replace the word "apple" with "orange" in the string "I like apple".
text = "I like apple"
new_text = text.replace("apple", "orange")
print(new_text)

I like orange

In [11]:
# 6. Write a code to create a list with numbers 1 to 5 and print it.
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]

In [12]:
# 7. Write a code to append the number 10 to the list [1, 2, 3, 4].
list2 = [1,2,3,4]
list2.append(10)
print(list2)

[1, 2, 3, 4, 10]

In [13]:
# 8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].
list3 = [1,2,3,4,5]
list3.remove(3)
print(list3)

[1, 2, 4, 5]

In [14]:
# 9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].
list4 = ['a', 'b', 'c', 'd']
print(list4[1])

b

In [15]:
# 10. Write a code to reverse the list [10, 20, 30, 40, 50].
list5 = [10, 20, 30, 40, 50]
list5.reverse()
print(list5)

[50, 40, 30, 20, 10]

In [16]:
# 11. Write a code to create a tuple with the elements 100, 200, 300 and print it.
tuple1 = (100, 200, 300)
print(tuple1)

(100, 200, 300)

In [18]:
# 12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
tuple2 = ('red', 'green', 'blue', 'yellow')
print(tuple2[1:])

('green', 'blue', 'yellow')

In [19]:
# 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).
tuple3 = (10, 20, 5, 15)
print(min(tuple3))

5

In [20]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
tuple4 = ('dog', 'cat', 'rabbit')
print(tuple4.index('cat'))

1

In [23]:
# 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.
tuple5 = ("apple", "banana", "cherry")
print("kiwi" in tuple5)

False

In [24]:
# 16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.
set1 = {'a', 'b', 'c'}
print(set1)

{'b', 'a', 'c'}

In [25]:
# 17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
set2 = {1, 2, 3, 4, 5}
set2.clear()
print(set2)

set()

In [28]:
# 18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.
set3 = {1, 2, 3, 4}
set3.remove(4)
print(set3)

{1, 2, 3}

In [29]:
# 19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.
set4 = {1, 2, 3}
set5 = {3, 4, 5}
print(set4.union(set5))

{1, 2, 3, 4, 5}

In [30]:
# 20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.
set6 = {1, 2, 3}
set7 = {2, 3, 4}
print(set6.intersection(set7))

{2, 3}

In [31]:
# 21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
dict1 = {"name": "Ram", "age": 25, "city": "Noida"}
print(dict1)

{'name': 'Ram', 'age': 25, 'city': 'Noida'}

In [32]:
# 22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
dict2 = {'name': 'John', 'age': 25}
dict2["country"] = "USA"
print(dict2)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [33]:
# 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
dict3 = {'name': 'Alice', 'age': 30}
print(dict3["name"])

Alice

In [34]:
# 24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.
dict4 = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del dict4["age"]
print(dict4)

{'name': 'Bob', 'city': 'New York'}

In [35]:
# 25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.
dict5 = {'name': 'Alice', 'city': 'Paris'}
print("city" in dict5)

True

In [37]:
# 26. Write a code to create a list, a tuple, and a dictionary, and print them all.
list1 = [1,2,3,4]
tuple1 = (1,2,3,4)
dict1 = {"name": "Ram", "age": 25, "city": "Noida"}
print(list1)
print(tuple1)
print(dict1)

[1, 2, 3, 4]
(1, 2, 3, 4)
{'name': 'Ram', 'age': 25, 'city': 'Noida'}

In [38]:
# 27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced).
list1 = [31,92,73,49,5]
list1.sort()
print(list1)

[5, 31, 49, 73, 92]

In [39]:
# 28. Write a code to create a list with strings and print the element at the third index.
list2 = ["apple", "banana", "cherry", "date", "elderberry"]
print(list2[2])

cherry

In [44]:
# 29. Write a code to combine two dictionaries into one and print the result.
dict1 = {"name": "Ram", "age": 25, "city": "Noida"}
dict2 = {"country": "USA", "state": "California"}
dict1.update(dict2)
print(dict1)

{'name': 'Ram', 'age': 25, 'city': 'Noida', 'country': 'USA', 'state': 'California'}

In [46]:
# 30. Write a code to convert a list of strings into a set.
list1 = ["apple", "banana", "cherry", "date", "elderberry"]
set1 = set(list1)
print(set1)

{'date', 'cherry', 'banana', 'apple', 'elderberry'}